### ISSUE TITLE
Change Nexus domain into rework-space.com

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/ambari#11]
## Description
Nexus is available at https://nexus-rm.rework-space.com/ now. It will be good to change Nexus url for Ambari build.

## Tasks
- [x] Change Nexus domain into rework-space.com
- [x] Upgrade version into 2.7.8.2.0
- [x] Build Ambari  and upload artifacts on Nexus
